INSERT INTO MEDICINE (MEDICINE_ID, MEDICINE_NAME, BRAND, DESCRIPTION, TREATABLE_DISEASES, PRICE, QUANTITY) VALUES (1, 'Albuterol', 'Proair HFA', 'Relaxes muscles in the airways and increase air flow to lungs', 'asthma', 100.00, 123)

INSERT INTO USERS (USER_ID, USERNAME, ROLE, FIRST_NAME, LAST_NAME, PASSWORD, BIRTH_DATE, PHONE_NUMBER, EMAIL, ADDRESS) VALUES (34, 'john_doe', 'ADMIN', 'John', 'Doe', 'password', '2016-11-09', '505-223-1234', 'johndoe@email.com', '123 pineapple rd')

INSERT INTO ORDERS (ORDER_ID, USER_ID, ORDER_STATUS, ORDER_DATE) VALUES (12345, 34, 'SHIPPED', '2016-11-09')

INSERT INTO ORDER_ITEMS(ID, QUANTITY, MEDICINE_ID, ORDER_ID) VALUES (2222, 2, 1, 12345)

INSERT INTO CART (CART_ID, CART_COST, USER_ID) VALUES (5454, 0.00, 34)

INSERT INTO CART_ITEM (CART_ITEM_ID, CART_ID, MEDICINE_ID, QUANTITY) VALUES (1, 5454, 1, 1)